### ISSUE TITLE
Compatibility issue with sbt-js-engine Tireme/Rhino (Play 2.6)

### ISSUE THREAD

**Issue by llb4ll** [sbt/sbt-less#95] opened 2017-08-16 08:18 UTC
There is a compatibility issue with sbt-js-engine versions for Play 2.6 that results in errors for the less compilation. See https://github.com/sbt/sbt-js-engine/issues/56.

The build works fine with JsEngine Node but fails for Tireme / Rhino with the following error:

```
[info] LESS compiling on 1 source(s)
[error] java.lang.NoSuchMethodError: org.mozilla.javascript.ScriptRuntime.setObjectProp(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;Lorg/mozilla/javascript/Context;Lorg/mozilla/javascript/Scriptable;)Ljava/lang/Object;
[error]         at io.apigee.trireme.node10.main.trireme._c_anonymous_1(trireme.js:37)
[error]         at io.apigee.trireme.node10.main.trireme.call(trireme.js)
[error]         at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
[error]         at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3102)
[error]         at io.apigee.trireme.node10.main.trireme.call(trireme.js)
[error]         at io.apigee.trireme.core.internal.ScriptRunner.runScript(ScriptRunner.java:762)
[error]         at io.apigee.trireme.core.internal.ScriptRunner$4.run(ScriptRunner.java:702)
[error]         at org.mozilla.javascript.Context.call(Context.java:488)
[error]         at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
[error]         at io.apigee.trireme.core.internal.ScriptRunner.call(ScriptRunner.java:697)
[error]         at io.apigee.trireme.core.ScriptFuture.run(ScriptFuture.java:183)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
```

Upgrading sbt-js-engine might resolve this.

**Comment by benmccann** [comment] 2017-08-24 02:24
Can you try with the new 1.1.2 release?

**Comment by eugengarkusha** [comment] 2017-08-25 16:53
@benmccann , updating less version to 1.1.2 did not fix problem for me.
Also I have tried to delete 'target' directory or switch to less 1.0.6  as advised here(https://github.com/sbt/sbt-less/issues/68) and it also did not help.
 Environment: MacOs: 10.11.6, sbt: 0.13.15, java : 1.8.0_74, play : 2.6.0, less: 1.1.2

**Comment by jroper** [comment] 2017-09-04 02:02
I can't reproduce this. The error that you're seeing indicates that the version of Trireme and the version of Rhino being used are not compatible with each other. This is not likely to be anything to do with sbt-less or sbt-js-engine, rather it's like that you're using another sbt plugin that is transitively upgrading or downgrading either Trireme or Rhino and causing this problem. Could you minimise the problem into a reproducer so that we can investigate further?

**Comment by jroper** [comment] 2017-09-04 02:09
Alternatively, you could attach the following file.

If using sbt 0.13.15 or earlier:

    project/target/resolution-cache/reports/default-<yourprojectname>-build-compile.xml

If using sbt 0.13.16:

    project/target/scala-2.10/sbt-0.13/resolution-cache/reports/default-<yourprojectname>-build-compile.xml

If using sbt 1.0.0 or later:

    project/target/scala-2.12/sbt-1.0/resolution-cache/reports/default-<yourprojectname>-build-compile.xml

This file will show exactly what versions of what libraries your build is using and why.

**Comment by benmccann** [comment] 2017-09-07 02:41
Also, can you try running `find . -name target | xargs rm -rf` and then running again to see if that fixes the problem? We've found that some people have run into some caching issues https://github.com/sbt/sbt-less/issues/80

**Comment by eugengarkusha** [comment] 2017-09-08 08:23
@benmccann this unfortunately did not help, thanks.
@jroper Thanks much for your attention to this problem. I have worked it around by installing NodeJs and adding the following to my .bash_profile
export SBT_OPTS="${SBT_OPTS} -Dsbt.jse.engineType=Node -Dsbt.jse.command=$(which node)"

**Comment by jroper** [comment] 2017-09-08 22:34
If node is on your path (which it is, since you're finding it using `which node`, then you shouldn't need to explicitly tell sbt to use node, since it should detect it itself.

**Comment by eugengarkusha** [comment] 2017-09-09 00:10
@jroper thanks, ill remove that export.

**Comment by wongelz** [comment] 2018-06-06 14:05
I've reproduced the problem in the following repo: https://github.com/wongelz/scalajs-tutorial

**Comment by jroper** [comment] 2018-06-06 23:48
So, scalajs depends on an Apigee build of Rhino (and it seems to be some sort of non standard pre release, so it's probably doing the wrong thing here), `org.apigee:rhino:1.7R5pre4`:

https://github.com/scala-js/scala-js/blob/52f989bc801eb2754f8897daa01728429139203f/project/Build.scala#L1801

Meanwhile, sbt js-engine depends on Trireme 0.8.9, which oddly enough depends on the Mozilla Rhino build, `org.mozilla:rhino:1.7.7.1`:

https://github.com/apigee/trireme/blob/trireme-0.8.9/pom.xml#L72-L76

I haven't looked in detail, but presumably both of these versions are on the classpath, but they are not binary compatible.

You should be able to fix sbt-less by adding this to `plugins.sbt`:

```scala
excludeDependencies += "org.apigee" % "rhino"
```

However, that may break scalajs. If it does, to actually solve the problem, the conflict will need to be resolved - either Trireme will need to move to the apigee rhino version, or scala js will need to move to the Mozilla rhino version, and they'll both need to be on versions that are binary compatible with each other. I would actually say that scala-js is at fault, given that it's not even depending on a final release Rhino but a pre release, and it should move to a more standard version of rhino in order to play nicely with other libraries out there.

Regardless, the root cause here is not in sbt-less, so I'm closing.

**Closed by jroper** 2018-06-06 23:48 UTC
