### ISSUE TITLE
Version 2.6.2 of play doesn't compile .less files to .css files

### ISSUE THREAD

**Issue by DragomirAdapptive** [sbt/sbt-less#98] opened 2017-08-24 13:57 UTC
I've asked a question on [SO](https://stackoverflow.com/questions/45861021/play-framework-with-less-css) .  In short, I have followed your documentation steps and my target folder doesn't seem to be converting .less files into .css files. So my stylesheet tags don't seem to be working at all. Is there something I'm missing ? I'm using scala version 2.12.2.

**Comment by benmccann** [comment] 2017-08-28 01:55
Please close as a duplicate of https://github.com/sbt/sbt-less/issues/95

Provided a solution on StackOverflow

**Closed** 2017-09-04 01:50 UTC
